### PR TITLE
feat: mobile navigation

### PR DESCRIPTION
**Pull request by michaelfurutin**
localhost_3000_teams_team_920b56b54e1f3ddb17cb49484ad67f5d (2)

### CODE REVIEW

**Review by igorosip0v — COMMENTED** [review]
@michaelfurutin On the Sign in with World ID page some of the elements (app id input I assume) have no proper min width and pushing form width 

<details>
<summary>Screenshot</summary>

image

</details>

**Comment by igorosip0v** [comment]
@michaelfurutin Profile page on the desktop is not centered and broken

<details>
<summary>Screenshot</summary>

image

</details>

**Comment by igorosip0v** [comment]
@michaelfurutin On the action page top navigation looks a bit off. Looks like current tab bubble have too much padding or something like this

<details>
<summary>Screenshot</summary>

image

</details>

**Comment by michaelfurutin** [comment]
> @michaelfurutin Profile page on the desktop is not centered and broken
> 
> Screenshot
> image

fixed

**Comment by michaelfurutin** [comment]
> @michaelfurutin On the action page top navigation looks a bit off. Looks like current tab bubble have too much y padding or something like this
> 
> Screenshot
> image

fixed

**Comment by michaelfurutin** [comment]
> @michaelfurutin On the Sign in with World ID page some of the elements (app id input I assume) have no proper min width and pushing form width
> 
> Screenshot
> image

fixed

**Review by igorosip0v — APPROVED** [review]

**Pull request merged**
